### ISSUE TITLE
大佬辛苦了，我是一名英语老师，想把您的作品中的部分图片替换成英语词汇辅助教学，不知道能不能允许下载一份代码

### ISSUE THREAD

**Issue by GeekZed** [HumanSean/javascript-monopoly#4]

**Comment by HumanSean** [comment]
十分欢迎！具体是怎么替换呢？我也是一名英专生，对此很感兴趣

**Comment by GeekZed** [comment]
我的想法是把国家的名称换成英文单词，下面的空白处加上这个单词的对应图片，当学生掷色子到达某个地点后要先读出单词或者用该词造句才能购买，否则老师要求强制跳过购买环节，另外游戏人物以及命运机会等也可以添加上相应图片增加趣味性（PS我教的孩子年龄比较小0.0）

**Comment by GeekZed** [comment]
今天试玩了一下，事件弹窗的显示时间太短了，有些还没看清就消失，想请教下怎么修改自动消失时间，或者改成点击后消失也行

**Comment by HumanSean** [comment]
原来是这样。更改国家名称应该要在data.js里面设置。弹窗的话应该是在dom-binding.js里面的243行

**Comment by GeekZed** [comment]
收到。感谢！


 
---原始邮件---
发件人: "Human ***@***.***&gt;
发送时间: 2021年3月20日 10:08:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HumanSean/javascript-monopoly] 大佬辛苦了，我是一名英语老师，想把您的作品中的部分图片替换成英语词汇辅助教学，不知道能不能允许下载一份代码 (#4)




 
原来是这样。更改国家名称应该要在data.js里面设置。弹窗的话应该是在dom-binding.js里面的243行

**Comment by ZedCat** [comment]
// 显示消息框
function showMsgbox(msg){
	msgbox.style.display = "block"	
	msgbox.innerHTML = msg
	setTimeout(() => {
		msgbox.style.display = "none"
	},v * 1.6)
}
尝试直接修改速度 v*1.6  结果没变化，求教
1.V后面的参数是不是越大消息弹窗消失的速度越慢？
2.修改后是不是需要重新打包生成index.js才会生效？npm install 后 使用什么命令打包？

**Comment by ZedCat** [comment]
thanks for help！
